spring:
  redis:
    host: 127.0.0.1
    password: 123456
    database: 8
    port: 6379
    timeout: 5000
    testOnBorrow: true
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000